from selenium import webdriver
from selenium.webdriver.common.by import By
from Test_Data import data
import pytest
import time

class Test_OrangeHRM:
    url = "https://opensource-demo.orangehrmlive.com/"
    
    # Booting function for running the python tests
    @pytest.fixture
    def booting_function(self):
        self.driver = webdriver.Firefox()
        # self.driver.maximize_window
        yield
        self.driver.close()

    def test_TC_PIM_01(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.username_NAME).send_keys(data.OrangeHRM_Login.username)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.password_NAME).send_keys(data.OrangeHRM_Login.password)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Login.login_XPATH).click()
        time.sleep(4)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.admin)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Admin_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.pim)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.leave)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Leave_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.time)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Time_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.recruitment)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Recruitment_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.my_info)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.My_Info_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.performance)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Performance_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.dashboard)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Dashboard_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.directory)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Directory_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.maintenance)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Maintenance_NAME).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.cancel).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.buzz)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Buzz_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.ADMIN)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Admin_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.PIM)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.LEAVE)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Leave_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.TIME)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Time_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.RECRUITMENT)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Recruitment_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.MY_INFO)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.My_Info_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.PERFORMANCE)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Performance_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.DASHBOARD)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Dashboard_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.DIRECTORY)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Directory_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.MAINTENANCE)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Maintenance_NAME).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.cancel).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Search.search).send_keys(data.OrangeHRM_Search.BUZZ)
        time.sleep(1)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Buzz_NAME).click()
        time.sleep(2)
        print("SUCCESS # Searched the admin page menu successfully")
        
    def test_TC_PIM_02(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.username_NAME).send_keys(data.OrangeHRM_Login.username)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.password_NAME).send_keys(data.OrangeHRM_Login.password)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Login.login_XPATH).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.Admin_NAME).click()
        time.sleep(3)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Admin.user_management).click()
        time.sleep(2)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Admin.users).click()
        time.sleep(4)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Admin.user_role).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Admin.user_role_admin).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Admin.user_role).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Admin.user_role_ESS).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Admin.admin_status).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Admin.admin_status_Disabled).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Admin.admin_status).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Admin.admin_status_Enabled).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Admin.search).click()
        time.sleep(2)
        print("SUCCESS # User Role Dropdown and Status Dropdown can be seen ssuccessfully")
    
    def test_TC_PIM_03(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.username_NAME).send_keys(data.OrangeHRM_Login.username)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.password_NAME).send_keys(data.OrangeHRM_Login.password)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Login.login_XPATH).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(3)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Add.add).click()
        time.sleep(3)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Add.firstname_NAME).send_keys(data.OrangeHRM_Add.firstname)
        time.sleep(1)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Add.middlename_NAME).send_keys(data.OrangeHRM_Add.middlename)
        time.sleep(1)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Add.lastname_NAME).send_keys(data.OrangeHRM_Add.lastname)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Add.create_login_details).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Add.PIM_status).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Add.PIM_username_XPATH).send_keys(data.OrangeHRM_Add.PIM_username)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Add.PIM_password_XPATH).send_keys(data.OrangeHRM_Add.PIM_password)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Add.PIM_confirm_password).send_keys(data.OrangeHRM_Add.PIM_password)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Add.PIM_save).click()
        time.sleep(5)
        print("SUCCESS # New Employee added with login details successfully")
        
    def test_TC_PIM_04(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.username_NAME).send_keys(data.OrangeHRM_Login.username)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.password_NAME).send_keys(data.OrangeHRM_Login.password)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Login.login_XPATH).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Contact_Details).click()
        time.sleep(2)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Personal_Details).click()
        time.sleep(2)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Emergency_Contacts).click()
        time.sleep(2)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Dependents).click()
        time.sleep(2)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Immigration).click()
        time.sleep(2)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Job).click()
        time.sleep(2)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Salary).click()
        time.sleep(2)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Tax_Exemptions).click()
        time.sleep(2)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Report_to).click()
        time.sleep(2)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Qualifications).click()
        time.sleep(2)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Memberships).click()
        time.sleep(4)
        print("SUCCESS # Tabs are present under the Employee List")
        
    def test_TC_PIM_05(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.username_NAME).send_keys(data.OrangeHRM_Login.username)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.password_NAME).send_keys(data.OrangeHRM_Login.password)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Login.login_XPATH).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Personal_Details.Nickname_XPATH).send_keys(data.OrangeHRM_Personal_Details.Nickname)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Personal_Details.Other_ID_XPATH).send_keys(data.OrangeHRM_Personal_Details.Other_ID)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Personal_Details.Driver_License_Number_XPATH).send_keys(data.OrangeHRM_Personal_Details.Driver_License_Number)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Personal_Details.License_Expiry_Date_XPATH).send_keys(data.OrangeHRM_Personal_Details.License_Expiry_Date)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Personal_Details.SSN_Number_XPATH).send_keys(data.OrangeHRM_Personal_Details.SSN_Number)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Personal_Details.SIN_Number_XPATH).send_keys(data.OrangeHRM_Personal_Details.SIN_Number)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Personal_Details.Nationality).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Personal_Details.Country).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Personal_Details.Marital_Status).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Personal_Details.Status).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Personal_Details.DOB_XPATH).send_keys(data.OrangeHRM_Personal_Details.DOB)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Personal_Details.Gender).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Personal_Details.Military_XPATH).send_keys(data.OrangeHRM_Personal_Details.Military)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Personal_Details.Save_XPATH).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Personal_Details.Blood_Type).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Personal_Details.Blood).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Personal_Details.Save_Blood_Group).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(5)
        print("SUCCESS # Personal Details added successfully")
        
    def test_TC_PIM_06(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.username_NAME).send_keys(data.OrangeHRM_Login.username)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.password_NAME).send_keys(data.OrangeHRM_Login.password)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Login.login_XPATH).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Contact_Details).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Contact_Details.Address_street1_XPATH).send_keys(data.OrangeHRM_Contact_Details.Address_street1)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Contact_Details.Address_street2_XPATH).send_keys(data.OrangeHRM_Contact_Details.Address_street2)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Contact_Details.city_XPATH).send_keys(data.OrangeHRM_Contact_Details.city)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Contact_Details.state_XPATH).send_keys(data.OrangeHRM_Contact_Details.state)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Contact_Details.zip_XPATH).send_keys(data.OrangeHRM_Contact_Details.zip)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Contact_Details.country_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Contact_Details.India).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Contact_Details.home_phone_number_XPATH).send_keys(data.OrangeHRM_Contact_Details.home_phone_number)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Contact_Details.Mobile_number_XPATH).send_keys(data.OrangeHRM_Contact_Details.Mobile_number)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Contact_Details.work_phone_number_XPATH).send_keys(data.OrangeHRM_Contact_Details.work_phone_number)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Contact_Details.email_ID_XPATH).send_keys(data.OrangeHRM_Contact_Details.email_ID)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Contact_Details.other_email_ID_XPATH).send_keys(data.OrangeHRM_Contact_Details.other_email_ID)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Contact_Details.save).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(8)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Contact_Details).click()
        time.sleep(3)
        print("SUCCESS # Contact Details added successfully")
        
    def test_TC_PIM_07(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.username_NAME).send_keys(data.OrangeHRM_Login.username)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.password_NAME).send_keys(data.OrangeHRM_Login.password)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Login.login_XPATH).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Emergency_Contacts).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Emergency_Contact_Details.Add_XPATH).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Emergency_Contact_Details.name_XPATH).send_keys(data.OrangeHRM_Emergency_Contact_Details.name)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Emergency_Contact_Details.relationship_XPATH).send_keys(data.OrangeHRM_Emergency_Contact_Details.relationship)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Emergency_Contact_Details.home_phone_number_XPATH).send_keys(data.OrangeHRM_Emergency_Contact_Details.home_phone_number)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Emergency_Contact_Details.Mobile_number_XPATH).send_keys(data.OrangeHRM_Emergency_Contact_Details.Mobile_number)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Emergency_Contact_Details.work_phone_number_XPATH).send_keys(data.OrangeHRM_Emergency_Contact_Details.work_phone_number)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Emergency_Contact_Details.save).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Emergency_Contacts).click()
        time.sleep(3)
        print("SUCCESS # Emergency Contact Details added successfully")
    
    def test_TC_PIM_08(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.username_NAME).send_keys(data.OrangeHRM_Login.username)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.password_NAME).send_keys(data.OrangeHRM_Login.password)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Login.login_XPATH).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Dependents).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Dependents.Add_XPATH).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Dependents.Name_XPATH).send_keys(data.OrangeHRM_Dependents.Name)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Dependents.relationship_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Dependents.others_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Dependents.specify_XPATH).send_keys(data.OrangeHRM_Dependents.specify)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Dependents.DOB_XPATH).send_keys(data.OrangeHRM_Dependents.DOB)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Dependents.save).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Dependents).click()
        time.sleep(3)
        print("SUCCESS # Dependency Details added successfully")
        
    
    def test_TC_PIM_09(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.username_NAME).send_keys(data.OrangeHRM_Login.username)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.password_NAME).send_keys(data.OrangeHRM_Login.password)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Login.login_XPATH).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Job).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_job.Joined_Date_XPATH).send_keys(data.OrangeHRM_job.Joined_Date)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_job.Job_Title_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_job.Job_Title_Dropdown).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_job.Job_Category_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_job.Operatives).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_job.Sub_Unit_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_job.Client_Services).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_job.Location_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_job.HQ_CA_USA).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_job.Employment_status_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_job.Full_Time_Permanent).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_job.Contract_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_job.Start_Date_XPATH).send_keys(data.OrangeHRM_job.Start_Date)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_job.End_Date_XPATH).send_keys(data.OrangeHRM_job.End_Date)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_job.Save_XPATH).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(3)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Job).click()
        time.sleep(3)
        print("SUCCESS # Job Details added successfully")
        
    def test_TC_PIM_10(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.username_NAME).send_keys(data.OrangeHRM_Login.username)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.password_NAME).send_keys(data.OrangeHRM_Login.password)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Login.login_XPATH).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Job).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Termination.Terminate_Employment_XPATH).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Termination.Termination_Date_XPATH).send_keys(data.OrangeHRM_Termination.Termination_Date)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Termination.Termination_Reason_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Termination.Retired_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Termination.Note_XPATH).send_keys(data.OrangeHRM_Termination.Note)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Termination.Save_XPATH).click()
        time.sleep(7)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Employee_Activation.Activate_Employment_XPATH).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Job).click()
        time.sleep(4)
        print("SUCCESS # Employee Termination done successfully")
        
    def test_TC_PIM_11(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.username_NAME).send_keys(data.OrangeHRM_Login.username)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.password_NAME).send_keys(data.OrangeHRM_Login.password)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Login.login_XPATH).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Job).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Termination.Terminate_Employment_XPATH).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Termination.Termination_Date_XPATH).send_keys(data.OrangeHRM_Termination.Termination_Date)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Termination.Termination_Reason_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Termination.Retired_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Termination.Note_XPATH).send_keys(data.OrangeHRM_Termination.Note)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Termination.Save_XPATH).click()
        time.sleep(7)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Employee_Activation.Activate_Employment_XPATH).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Job).click()
        time.sleep(4)
        print("SUCCESS # Employee Activation done successfully")
        
    def test_TC_PIM_12(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.username_NAME).send_keys(data.OrangeHRM_Login.username)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.password_NAME).send_keys(data.OrangeHRM_Login.password)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Login.login_XPATH).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Salary).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Salary_Details.Add_Salary_XPATH).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Salary_Details.Salary_Components_XPATH).send_keys(data.OrangeHRM_Salary_Details.Salary_Components)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Salary_Details.Pay_Grade_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Salary_Details.Grade_3_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Salary_Details.Pay_Frequency_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Salary_Details.Monthly_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Salary_Details.Currency_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Salary_Details.Currency_Dropdown).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Salary_Details.Amount_XPATH).send_keys(data.OrangeHRM_Salary_Details.Amount)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Salary_Details.Comment_XPATH).send_keys(data.OrangeHRM_Salary_Details.Comment)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Salary_Details.Include_Direct_Deposit_Details_XPATH).click()
        time.sleep(4)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Salary_Details.Account_Number_XPATH).send_keys(data.OrangeHRM_Salary_Details.Account_Number)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Salary_Details.Account_Type_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Salary_Details.Savings_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Salary_Details.Routing_Number_XPATH).send_keys(data.OrangeHRM_Salary_Details.Routing_Number)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Salary_Details.Salary_Amount_XPATH).send_keys(data.OrangeHRM_Salary_Details.Amount)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Salary_Details.Save_XPATH).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Salary).click()
        time.sleep(2)
        print("SUCCESS # Salary Details added successfully")
        
    def test_TC_PIM_13(self,booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.username_NAME).send_keys(data.OrangeHRM_Login.username)
        self.driver.find_element(by = By.NAME, value=data.OrangeHRM_Login.password_NAME).send_keys(data.OrangeHRM_Login.password)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Login.login_XPATH).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Tax_Exemptions).click()
        time.sleep(2)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Tax_Exemptions.Federal_Status_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Tax_Exemptions.Single_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Tax_Exemptions.Exemptions_XPATH).send_keys(data.OrangeHRM_Tax_Exemptions.Exemptions)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Tax_Exemptions.State_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Tax_Exemptions.Tennessee_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Tax_Exemptions.State_Status_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Tax_Exemptions.Single_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Tax_Exemptions.State_Exemptions_XPATH).send_keys(data.OrangeHRM_Tax_Exemptions.Exemptions)
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Tax_Exemptions.Unemployment_State_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Tax_Exemptions.Tennessee_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Tax_Exemptions.Work_State_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Tax_Exemptions.Tennessee_XPATH).click()
        time.sleep(1)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Tax_Exemptions.Save_XPATH).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Search.PIM_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.XPATH, value=data.OrangeHRM_Edit.employee_NAME).click()
        time.sleep(5)
        self.driver.find_element(by = By.LINK_TEXT, value=data.OrangeHRM_Edit.Tax_Exemptions).click()
        time.sleep(2)
        print("SUCCESS # Tax Exemptions Details added successfully")